### PR TITLE
Update TUSD address and add TCAD

### PR DESCRIPTION
**Pull request by wjmelements**
#### Changes
This lists the TCAD uniswap for the frontend and updates the TUSD address.
I set up the TCAD uniswap manually and gave it initial funding.
We want to send our users your way if they want to trade TCAD because your interface is superior to Etherscan.
#### TUSD Upgrade
I believe the TUSD address is safe to update.
We announced the upgrade one month in advance [here](https://blog.trusttoken.com/upgrade-80ba355f8960).
The TUSD contract upgrade was performed atomically on 4 January 2019 at 3am UTC in tx 0x81c880de8f67362cb4792990560a6adf9aab819bbe28e334867ce8e4f88415a6
The old contract address uses DelegateERC20, so it forwards all of the ERC20 requests, including approvals, to the new address.
All TUSD balances and approvals are the same regardless of which contract you use.
That is, ERC20 approve at the old address is equivalent to ERC20 approve at the new address, but with the old address there is about 5000 gas overhead.
We do not wish to split the ~$250k TUSD Uniswap liquidity, but we do wish to help people save the gas overhead of the delegation.
Reviewers @NoahZinsmeister

### CODE REVIEW

**Comment by haydenadams** [comment]
@wjmelements 

add it here!

https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets

**Comment by wjmelements** [comment]
@haydenadams Thanks; added here: https://github.com/trustwallet/assets/pull/200

**Comment by wjmelements** [comment]
The asset PR has merged.

**Comment by NoahZinsmeister** [comment]
@wjmelements going to get this merged tomorrow!

**Comment by wjmelements** [comment]
Thanks. Let us know when this is live. We would prefer for our trader to use the official UI to load additional liquidity.

**Comment by haydenadams** [comment]
@wjmelements @NoahZinsmeister 

A liquidity provider appears to have pulled almost all liquidity out of the pair (potentially in anticipation of the upgrade. If we want to update to the new exchange address (the address associated w/ the new token address) now would be a fine time.

**Comment by wjmelements** [comment]
Nice, will do

**Comment by wjmelements** [comment]
They sent it to Binance, so they may not seed liquidity in the new exchange, but I am less hesitant to update the exchange address with the substantially reduced liquidity. I have made this change.

**Pull request merged**
