### PR TITLE
New sUSD exchange and removed old sETH exchange

### PR DESCRIPTION
**Pull request by hav-noms**
**PLEASE DO NOT SUBMIT TOKEN ADDITIONS AS PULL REQUESTS**

All token requests should be made via an issue.

### CODE REVIEW

**Comment by hav-noms** [comment]
@NoahZinsmeister this one is kinda urgent if you can take a look please

**Comment by NoahZinsmeister** [comment]
Please checksum the contract addresses @hav-noms, then I can merge.

**Comment by NoahZinsmeister** [comment]
Also why the new sUSD contract? It looks like it has no liquidity right now.

**Comment by hav-noms** [comment]
@NoahZinsmeister checksummed sUSD. 

We upgraded the all synth proxies to be ERC20 compatible with balanceOf(). So we dont have to replace any of the uniswap exchanges ever again. *fingerscrossed

Kain will add liquidity when it's up. He didn't seem to be in a rush. The Synthetix foundation is the main liquidity provider for sUSD. I'll ping him to add now.

**Pull request merged**
