### PR TITLE
Make Swap input’s Balance text act as a “Set max” button

### PR DESCRIPTION
**Pull request by mikedemarais**
Fixes https://github.com/Uniswap/uniswap-frontend/issues/154

mobile:

desktop:

### CODE REVIEW

**Comment by chikeichan** [comment]
Thanks @mikedemarais !

This would work when we are swapping ERC20 tokens, but when we are swapping ETH, we have to account for the gas fee for the transaction. We have another issue to add calculation for suggested gas fee. Until that is done, can you adjust your pull request to only do this behavior for ERC20?

**Comment by WyseNynja** [comment]
Does this work the same way on the "Pool" tab?

I had a transaction fail because I tried to deposit the max of my token but the price moved a little and then I didn't have enough.  If I had clicked "transaction details" I would have seen that part of the range for my ERC20 token was too large for my balance.  But even if I had done that, there is no good way to make that number valid without some trial and error.

The "max" button on pooling should be the max that keeps the range inside a valid amount. People will get stuck with a cent or so of dust, but I think that's better than having the transaction revert and having to pay gas a second time.

**Comment by haydenadams** [comment]
@WyseNynja agreed there should at least be some sort of warning there

**Comment by ChristophSiegenthaler** [comment]
What I implemented on uniswap.ch is that it works as a set max button for ETH and tokens (only on the swap page so far), but it leaves 0.01 ETH in the account as a safety feature.

**Comment by NoahZinsmeister** [comment]
This is implemented on the beta branch for /send and /swap, clicking the input balance maxes out token balances and sets ETH balances to the current balance - .01 ETH. Pool and swap will require further discussion per @WyseNynja's comment above, which we can continue in a separate issue.

**Pull request closed without merging**
