### PR TITLE
Replaced AnimatedSwitch with Switch. Added CSS Animation

### PR DESCRIPTION
**Pull request by rossbulat**
AnimatedSwitch has been replaced with a vanilla CSS animation that fades in the content (after NavigationTabs - not sure why the header repeatedly faded in as nothing changes).

Why? AnimatedSwitch is very limiting beyond absolute positioning, something that is limiting Uniswap right now.

Look at the [drop in adoption](https://www.npmjs.com/package/react-router-transition) on NPMJS. 

If Uniswap is to become more modular we need to move to a more relative positioning model.

After this we can solve issues like the 5 x duplication of NavigationTabs, not being able to animate the tab bar, not being able to reposition the main content, etc...

### CODE REVIEW

**Comment by mikedemarais** [comment]
@rossbulat just read this over (but im on my iphone) so let me run this tmrw on my laptop and just make sure the animation effect is 👌✨ then

**Comment by rossbulat** [comment]
Animation made more subtle:

subtle animation

**Comment by mikedemarais** [comment]
thanks @rossbulat 
i’ve reached out to uniswaps UX lead @callil about what his original intentions for this tab animation were. will update this thread when i hear back.

**Comment by mirshko** [comment]
@mikedemarais @rossbulat I agree with @mikedemarais. that is quite a drastic animation, something less dramatic would be ideal. the existing one was a nice little fade but the new very simple transition is clean and nice 👍

**Comment by rossbulat** [comment]
> @mikedemarais @rossbulat I agree with @mikedemarais. that is quite a drastic animation, something less dramatic would be ideal. the existing one was a nice little fade but the new very simple transition is clean and nice 👍

Agreed. [This](https://github.com/Uniswap/uniswap-frontend/pull/186#issuecomment-452573488) more subtle transition feels nicer and more responsive than the original. 

@mikedemarais  Look forward to @callil response.

**Comment by callil** [comment]
I think the subtle option is a great improvement but it doesn't yet capture the full design intent.

I had designed this initially to have **no** flash when loading into the different views. The input elements should actually stay static and the _content inside_ should animate to change if required. 

In the case when a new field is added like the recipient address field, it should animate in and push the send button down fluidly.

If it would help to see an animation mockup I can throw that together.

**Comment by rossbulat** [comment]
@callil thanks for the great feedback, I'd be very interested to see a mockup of the vision.

> The input elements should actually stay static and the content inside should animate to change if required.

This. Modular, component based transitions would be a great goal to aim towards, and would certainly be the most aesthetically pleasing.

I believe with this PR accepted with the subtle fade, we can work to make this happen by moving to a relative positioning model, take DRY super seriously, and then experiment with more component-based transitions. I'd be committed to moving in this direction.

**Comment by mikedemarais** [comment]
@rossbulat hey, so all this being said, i think the best path forward is to merge just the part of this pull request that replaces `AnimatedSwitch` with `Switch`..

i think we should  remove the `.ani_title_fade_in {}` css class, and all the `<div />`'s its been added to... i think the app looks better with *no* animation until we can get it perfected.

so could you revert your changes to `App.scss` and remove the `<div className='ani_title_fade_in'>` wrappers you added in a couple places?

**Pull request merged**
