### PR TITLE
add GRG token

### PR DESCRIPTION
**Pull request by gabririgo**
Adding the GRG token.

For reference, see:

https://rigoblock.com
Token: https://etherscan.io/token/0x4FbB350052Bca5417566f188eB2EBCE5b19BC964
Exchange: https://etherscan.io/address/0xee5e8D2357A29F4a85a938679233fE24fbC2cf1D

### CODE REVIEW

**Comment by gabririgo** [comment]
@NoahZinsmeister hello. Can you please advise whether I did not follow the correct procedure and what the correct procedure for having GRG added is (uniswap reserve already created) ?

**Comment by NoahZinsmeister** [comment]
FYI: we will be monitoring token addition requests via issues going forward, feel free to open one!

**Comment by gabririgo** [comment]
> FYI: we will be monitoring token addition requests via issues going forward, feel free to open one!

hey @NoahZinsmeister I opened an issue the same day: https://github.com/Uniswap/uniswap-frontend/issues/294

 Can you please advise if everything is correct, and I will delete this branch? Thank you

**Comment by NoahZinsmeister** [comment]
@gabririgo yup, feel free to delete your branch!

**Comment by gabririgo** [comment]
@NoahZinsmeister deleting, thank you

**Pull request closed without merging**
