### PR TITLE
update SNX exchange and token address

### PR DESCRIPTION
**Pull request by hav-noms**

### CODE REVIEW

**Comment by NoahZinsmeister** [comment]
hi @hav-noms, could you comment on why Etherscan shows the token address you're updating as the 'upgraded token contract'? 

https://etherscan.io/address/0x3772f9716cf6d7a09ede3587738aa2af5577483a

**Comment by justinjmoses** [comment]
I'll jump in here @NoahZinsmeister as @hav-noms is in the APAC timezone. We have a proxy contract for our SNX token: https://etherscan.io/token/0xc011a72400e58ecd99ee497cf89e3775d4bd732f 

We've tried setting the Proxy contract address to Uniswap in the past but it failed repeatedly and lost funds and no one seems to know why. It's still an open investigation. 

As I mentioned in #297 (before subsequently closing it as it didn't have the new exchange set up), we upgraded the underlying `Synthetix` contract in block 7681827 - https://etherscan.io/tx/0x3e37069cf7cb6096cf689af928ca7ab78066d6c0921f0122ed12120fec9ca717. It's `target` is now: https://etherscan.io/address/0xEf8a2c1BC94e630463293F71bF5414d13e80F62D 

We are still waiting for Etherscan to process our request to add information and the SNX icon to the `0xEf8a2` address.

**Comment by NoahZinsmeister** [comment]
@justinjmoses got it, thanks for the background, makes sense! everything else looks good, just made some successful test swaps. updated SNX will be live on https://beta.uniswap.exchange in a few minutes, and we will merge to production shortly thereafter

**Comment by justinjmoses** [comment]
@NoahZinsmeister it looks like prod hasn't been merged yet - mind taking a look?

**Comment by NoahZinsmeister** [comment]
whoops, done! https://github.com/Uniswap/uniswap-frontend/pull/303

**Pull request merged**
