### PR TITLE
Permalink

### LINKED ISSUE #160: Feature request: permalink for swap/send/pool functionality per token (so people can link to a specific market)
People should be able to link (from other sites or in their communication) to a specific market, e.g.:

https://uniswap.exchange/swap#MKR
https://uniswap.exchange/send#DAI
https://uniswap.exchange/add-liquidity#tokenaddress

I am using an anchor (#) in the URL here, in the assumption that it is easier to implement in the current front end code (javascript picks up on the URL change and prefills the token symbol) than e.g. https://uniswap.exchange/swap/MKR (which would require a different backend).

### PR DESCRIPTION
**Pull request by A-w-K**
This pullrequest adds permalinks to **swap**, **send**, **add-liquidity**, **remove-liquidity** and **create-exchange** in order to allow links to prefill the required fields with any ERC-20 token that already has an exchange created with the uniswap protocol.

For tokens already added in the frontend hardcoded list the ticker symbol can be used instead of the token address.

### /swap
**input:** the input token
**output:** the output token
**amount:** the amount of tokens to sell

`/swap?input=DAI&output=0x1230x23d80c4ee8fb55d4183dd9329296e176dc7464e1&amount=1000`

this will prefill the swap interface for a trade to buy DONUTS worth 1000 DAI

### /send
**input:** the input token
**output:** the output token
**amount:** the amount of tokens to sell
**to:** to recipient of the output tokens

`/swap?input=ETH&output=0x1230x23d80c4ee8fb55d4183dd9329296e176dc7464e1&amount=1&to= 0x0000000000000000000000000000000000000000 `

this will buy 1 ETH worth of DONUTs and burn them by sending them to 0x0

### /create-Exchange
**token:** address of the token you want to create an exchange for

i don't really see the use for this, it's just here for completeness

### /add-liquidity
**token:** address of the token you want to provide liquidity for
**amount:** amount of tokens to add

### /remove-liquidity
**token:** address of the token you want to remove liquidity from
**amount:** amount of liquidity-tokens to remove

this PR should close #160

### CODE REVIEW

**Comment by A-w-K** [comment]
Any update on this @haydenadams @mikedemarais ?

**Comment by kingjacob** [comment]
@ChristophSiegenthaler (forked the front end as uniswap.ch) brought up the issue on Reddit of permalinks potentially being used by scammers e.g. a scammer could create a scam exchange and then use a uniswap.exchange/swap/ and people might think they're swapping DAI for ETH but instead be swapping DAI for ĒTH. 

Potential solutions could be restricting permalinks to symbols or throwing a warning to double check with a link to "https://etherscan.io/address/inuput-exchange-address" if the output token is a raw address.

**Comment by ChristophSiegenthaler** [comment]
I tried your suggested changes and it's mostly working. The form gets prefilled but the form doesn't get "recalculated" yet so one still has to "re-select" all the input fields to correctly set them. Any ideas?

**Comment by pascalvanhecke** [comment]
I understand from a conversation on Slack that there is a (justified) reluctance to accept this pull request because people can create scam tokens - e.g. deploy an ERC20 token with exactly the same name and symbol as an existing token that has value in the market, and assigning the distribution to themselves.

Including such and address in a Uniswap URL would then trick people into buying these (valueless) tokens with tokens or ETH that do have a real market price.

Can I suggest to @A-w-K to include this warning in case an address is used instead of an already registered token symbol:

"Warning: you clicked a link that prefilled the dropdown with the token with symbol <SYMBOL>, name <name> and address <address>.  

Please be aware that anyone can create a token with this name and symbol, even if there exist already other tokens with that name or symbol.  You need to verify for yourself that the token at address <address> really is the token you want to swap, send, or provide liquidity for.  

The hoster of this website has not selected or verified the token at address and cannot be held responsible for any damages you incur."

**Pull request closed without merging**
