### PR TITLE
Inverted exchange rate added

### PR DESCRIPTION
**Pull request by ChristophSiegenthaler**

### CODE REVIEW

**Comment by phraktle** [comment]
This is very useful detail, please merge :)

**Comment by ChristophSiegenthaler** [comment]
> 
> 
> This is very useful detail, please merge :)

While waiting for this to be merged feel free to use it on uniswap.ch

**Comment by ChristophSiegenthaler** [comment]
What's up with this one? I can't be the only one that finds this useful, can I?

**Comment by NoahZinsmeister** [comment]
It's being added pending a major app re-write :) look out for it in the next few days!

**Comment by NoahZinsmeister** [comment]
@ChristophSiegenthaler https://twitter.com/NoahZinsmeister/status/1123121090870509568

**Comment by ChristophSiegenthaler** [comment]
@NoahZinsmeister Awesome, looking forward to the new uniswap :)

**Pull request closed without merging**
