### PR TITLE
add shell.nix and HOT token

### PR DESCRIPTION
**Pull request by thedavidmeister**
this does two things:

1. adds `shell.nix` file to pull in necessary development deps for nixos (python, node, yarn, udev)
2. adds HOT token to hardcoded address lists

as per reddit posts:

- https://www.reddit.com/r/UniSwap/comments/bjc50o/hot_and_presumably_other_tokens_not_immediately/
- https://www.reddit.com/r/UniSwap/comments/awjle9/why_is_hot_not_accessible_to_swap_tokens_when_is/

HOT does not appear on load, but will appear through workaround manually pasting contracts into the UI

HOT contract can be found on etherscan.io

https://etherscan.io/address/0x6c6ee5e31d828de241282b9606c8e98ea48526e2

uniswap exchange pulled from explorer, visible on etherscan.io

https://etherscan.io/address/0xd4777e164c6c683e10593e08760b803d58529a8e

IIRC the k/v map simply lines the two addresses up

there is currently ~6 million HOT locked into liquidity atm (roughly $15 000 USD inc. ETH) that cannot be accessed by users

### CODE REVIEW

**Comment by thedavidmeister** [comment]
@NoahZinsmeister can i get a review/merge here?

**Comment by NoahZinsmeister** [comment]
@thedavidmeister working a re-write that's going to change the structure of tokens a bit, if you don't mind holding tight for a week or so. what's `shell.nix` and why is it in this PR?

**Comment by thedavidmeister** [comment]
@NoahZinsmeister i'd love to merge it now if there's no issues under the current paradigm

is there a reason why adding this now would delay the refactor?
what can i do to ensure that HOT is available from day 1 in the refactor?

several ppl in the HOT community have asked about adding liquidity to the pair and i've recommended they hold off until this is resolved in the UI

`shell.nix` is like `package.json` for the nixos OS - https://nixos.org/
that's the OS that Holo runs for holoports
the standalone nix package manager runs on both linux and mac - https://nixos.org/nix/download.html
anyone who runs `nix-shell` will autodetect the `shell.nix` file, which will give them yarn and a few other dependencies so they can run `yarn` and `yarn start` and have it work
i added this because the instructions in the README to run `yarn start` didn't work for me until i added a few things like python, udev and a relatively recent node version

**Comment by NoahZinsmeister** [comment]
we're freezing dev on the old codebase, and don't have the bandwidth to review PRs right now, trivial as they may seem.

rest assured that we are working overtime on this, and are aiming to have a beta release available no later than sunday/monday, and in all likelihood a production one soon thereafter.

re. the nix file, i don't think we'll be adding this, seems a bit too niche. i'll maybe add some instructions about installing node/yarn in the readme.

i will make sure that hot is available in the default tokenlist by the time the beta launches :)

**Comment by thedavidmeister** [comment]
@NoahZinsmeister 

> rest assured that we are working overtime on this, and are aiming to have a beta release available no later than sunday/monday, and in all likelihood a production one soon thereafter.

cool, i'm in denver for a week so i won't be able to look at this much more till after the 15th anyway

> i will make sure that hot is available in the default tokenlist by the time the beta launches :)

great news!

less great news that the amount Noah Zinsmeister works and approves code has anything to do with the token list

i'm also looking at bootstrapping other tokens in the future, it would be good to document the process for community extensions to the default tokenlist (and to have it as decentralised as possible)

https://player.fm/series/unconfirmed-insights-and-analysis-from-the-top-minds-in-crypto/how-uniswap-quickly-became-one-of-the-most-popular-dexes-ep064

from about 18:20 seems relevant:

> LS: And who decides which tokens get listed on uniswap?
> HA: That's a good question, absolutely no-one

there is a tension here where we have these permissionless smart contracts but then we're all sitting around waiting on a gatekeeper to review and merge something into the standard client/UI that is the window into those contracts for the existing community (first HOT thread on reddit is 2 months old)

that's not a dig at you or the, it is the reality of the github model and the way the UI currently works with a hardcoded list of values

is there any chance that the rebuild would allow dynamic decentralised token lists in the UI to avoid this situation in the first place? how do GUIs like MEW work in this regard?

> re. the nix file, i don't think we'll be adding this, seems a bit too niche. i'll maybe add some instructions about installing node/yarn in the readme.

unfortunately it's not possible to install node/yarn by whatever method you're going to put in the readme on nixos
it is niche in the consumer world, but it is very well suited to crypto as it's the only way i know to achieve deterministic builds for decentralised software without heroic effort

- mozilla uses it https://github.com/mozilla/release-services/tree/master/nix and maintains rust overlays tracking nightly https://github.com/mozilla/nixpkgs-mozilla/blob/master/rust-overlay.nix
- holochain, obviously
- IOHK https://iohk.io/blog/how-we-use-nix-at-iohk/ (cardano and ETC)
- monero and parity integrations for 1-liner running full nodes:
  - `nix-shell -p parity --run parity`
  - `nix-shell -p monero --run monerod`

give it a whirl with the parity command above, see what you think :)

`curl https://nixos.org/nix/install | sh`

**Comment by martinkrung** [comment]
@thedavidmeister 

you have to change a different file to add your token,  see my commit here 530684d. Its  in alphabetical order,(SYMBOL)

**Comment by NoahZinsmeister** [comment]
added in the beta branch

**Comment by thedavidmeister** [comment]
@NoahZinsmeister awesome!

is the beta branch in a state where i can use it locally to test/transact, or should i hold off for now?

**Comment by NoahZinsmeister** [comment]
beta.uniswap.exchange!

**Comment by thedavidmeister** [comment]
@NoahZinsmeister oh great, i see it :)

i still have a few questions

1. what is the process for tokens in the future?
2. what's the ETA on the refactor hitting prod?
3. will there be any planned major changes to the beta branch between now and launch?

**Pull request closed without merging**
