### PR TITLE
Dynamic Search Icon / Cancel Search

### PR DESCRIPTION
**Pull request by rossbulat**
A concept to make the search icon functional, that also can cancel a search.

demo

The CSS could probably be tidied up somewhat. Can do additional testing if positive response is received from this.

### CODE REVIEW

**Comment by TingALin** [comment]
quite a useful idea

**Comment by callil** [comment]
++ 

please make the close icon a bit smaller and make sure it is aligned with the search icon. Right now it looks like it's slightly off.

All in all good improvement!

**Comment by rossbulat** [comment]
> make sure it is aligned with the search icon
Currently the bottom-left of the search icon rests on the middle point of the X. I would say the diameter of the glass circle is ~2px too large, decreasing it slightly would place it perfectly in the upper right quadrant of the X.

> make the close icon a bit smaller
Will submit a PR shortly with the amendments.

**Comment by rossbulat** [comment]
Latest commit: X is 10% smaller. Magnifying glass fits in upper right quadrant of X.

**Pull request closed without merging**
