### PR TITLE
Prioritize exact token symbol matches

### PR DESCRIPTION
**Pull request by GregTheGreek**
This adds an opinionated sort to the `filteredTokenList` to prioritize `DAI` when a user inputs `DAI` into the token search.

Previous:
Screen Shot 2020-02-12 at 10 06 42

New:
Screen Shot 2020-02-12 at 11 10 01

### CODE REVIEW

**Comment by NoahZinsmeister** [comment]
thanks for this @GregTheGreek 

a few comments:

1. the sort should happen when the filtered list is created, [here](https://github.com/Uniswap/uniswap-frontend/blob/bab5a1a5c6b9bc1b2c011bf168c8f8c1a983c665/src/components/CurrencyInputPanel/index.js#L570)

2. the same logic should apply to all exact symbol matches against `searchQuery`, and should be case-insensitive (see code earlier in that file for lowercased logic)

happy to merge once these two fixes are addressed!

**Comment by GregTheGreek** [comment]
@NoahZinsmeister I made some changes, let me know if thats what you wanted

**Comment by NoahZinsmeister** [comment]
i meant something more along the lines of:

```javascript
return (
  list.sort((a, b) => {
    return a.symbol.toLowerCase() === searchQuery.toLowerCase() ? -1 : 1
  })
)
```

also are we sure that sorting the list in this way isn't going to change the existing order?

**Comment by ChristophSiegenthaler** [comment]
Love the idea! When I apply the changes I get "exchange not found" on all querries except "dai", however.

**Comment by NoahZinsmeister** [comment]
@ChristophSiegenthaler yeah it's because the list isn't being returned unless the `searchQuery` matches DAI atm, which is wrong

**Comment by GregTheGreek** [comment]
> ```js
> return (
>   list.sort((a, b) => {
>     return a.symbol.toLowerCase() === searchQuery.toLowerCase() ? -1 : 1
>   })
> )
> ```

Right this makes sense, but to your point about the existing order, it breaks it. Thats why i prioritized DAI (should have returned everything otherwise). Personally, I feel like we can get away with isolating DAI since its one of the few things out there that have a lot of wrapped versions, otherwise just return the original list

**Comment by GregTheGreek** [comment]
(BTW i was AFK this weekend, so sorry for not responding)
Actually, here is an alternative approach:

```
if (searchQuery === "") return list;

return (
    list.sort((a, b) => {
        return a.symbol.toLowerCase() === searchQuery.toLowerCase() ? -1 : 1
    })
)
```

**Comment by NoahZinsmeister** [comment]
LGTM, thanks @GregTheGreek !

**Pull request merged**
